捕捉异常可以使用try/except语句。

```
try:
    fh = open("testfile", "w")
    fh.write("这是一个测试文件，用于测试异常!!")
except IOError:
    print "Error: 没有找到文件或读取文件失败"
else:
    print "内容写入文件成功"
    fh.close()


>>> try:
...     print('开始：')
...     r = 10 / int('2')
...     print('结果：',r)
... except ValueError as e:
...     print('ValueError:',e)
... except ZeroDivisionError as e:
...     print('ZeroDivision:',r)
... else:
...     print('没有出错！')
... finally:
...     print('最后要执行的代码')
...
开始：
结果： 5.0
没有出错！
最后要执行的代码
```

